export const ROUTES = {
  SIGN_IN: "/sign-in",
  HOME_PAGE: "/home-page",
  QNA: "/qna",
  QNA_PDF: "/qna/pdf",
  QNA_CSV: "/qna/csv",
  QNA_PDF_CHATTING: "/qna/pdf/chatting",
  QNA_CSV_CHATTING: "/qna/csv/chatting",
  CHATTING: "/chatting",
  DATA_ANALYST: "/data-analyst",
  DATA_ANALYST_CHATTING: "/data-analyst/chatting",
  ART_GENERATOR: "/art-generator",
  ART_GENERATOR_HISTORY: "/art-generator/history",
  ART_GENERATOR_HISTORY_DETAILS: "/art-generator/history/details",
  IMAGE_GENERATOR: "/art-generator/image-generator",
  AGENT_GPT: "/researcher",
  NEWSLETTER: "/newsletter",
  NEWSLETTER_CREATE: "/newsletter/create",
  NEWSLETTER_HISTORY: "/newsletter/history",
  NEWSLETTER_DETAILS: "/newsletter/details",
  PROSPECTOR: "/prospector",
  PROSPECTOR_DATA_TABLE: "/prospector/data-table",
  PROSPECTOR_SAVE_DATA_TABLE: "/prospector/save-data-table",
  WRITER: "/writer",
};
